### ISSUE TITLE
Code Release ?

### ISSUE THREAD

**Issue by AMEERAZAM08** [X-LANCE/AniTalker#1]

**Comment by hedada-hc** [comment]
There are currently no open source plans

**Comment by inferno46n2** [comment]
> There are currently no open source plans

So this is bullshit then. Noted 

![image](https://github.com/X-LANCE/AniTalker/assets/73665023/e175f0fa-f834-4269-8ca2-18253e1ba5eb)

**Comment by Inferencer** [comment]
> There are currently no open source plans

What makes you say that are you a part of the project in some way or just a gut feeling, I ask because people on this post are taking it as fact and it would be good to clarify.

**Comment by cacard** [comment]
没开源放到github会影响口碑

**Comment by johndpope** [comment]
side note - this paper is scheduled for code release soon - closer to VASA using diffusion transformer
https://github.com/andrerochow/fsrt 
https://andrerochow.github.io/fsrt/
https://arxiv.org/pdf/2404.09736

All of these papers can be mostly recreated in code using Claude Opus - so I wouldn't be too concerned if there's no code.
current works in progress 
https://github.com/johndpope/vasa-1-hack
https://github.com/johndpope/MegaPortrait-hack/

**Comment by ainrichman** [comment]
> side note - this paper is scheduled for code release soon - closer to VASA using diffusion transformer https://github.com/andrerochow/fsrt https://andrerochow.github.io/fsrt/ https://arxiv.org/pdf/2404.09736
> 
> All of these papers can be mostly recreated in code using Claude Opus - so I wouldn't be too concerned if there's no code. current works in progress https://github.com/johndpope/vasa-1-hack https://github.com/johndpope/MegaPortrait-hack/

fsrt is published last month, but no code util now.

**Comment by liutaocode** [comment]
Thanks for your attention. You can check it out now.
