### ISSUE TITLE
An alternative project EchoMimic is open-sourced

### ISSUE THREAD

**Issue by lymhust** [X-LANCE/AniTalker#14]
EchoMimic is capable of generating portrait videos not only by audios and facial landmarks individually, but also by a combination of both audios and selected facial landmarks.
Project link: https://badtobest.github.io/echomimic.html
GitHub link: https://github.com/BadToBest/EchoMimic
![image](https://github.com/X-LANCE/AniTalker/assets/18476076/195a67ac-9d3f-457f-abd7-8b261e84d016)

https://github.com/X-LANCE/AniTalker/assets/18476076/d3f6b8f8-a8ee-4332-b586-85bcfd3cc701

https://github.com/X-LANCE/AniTalker/assets/18476076/83b7dd63-0e24-4b1b-84de-8655ddb9a3b7

**Comment by liutaocode** [comment]
Wow~ I've also run this code. It's excellent, worth following.

**Comment by Arvrairobo** [comment]
but its vey slow, more then 2 hours of GPU time for 30 secs video generation, not useful for practical application.
