### ISSUE TITLE
How to create npy file from existing video for face and eyes movement

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#18]
Please excplain, how to generate npy file? 
NPY is a binary file format for storing data from the NumPy Python package.

**Comment by liutaocode** [comment]
To extract Hubert features for inference of your own audio, please refer to [this documentation](https://github.com/liutaocode/talking_face_preprocessing?tab=readme-ov-file#audio-feature-extraction) to obtain the Hubert feature. After extraction, place the feature path to `test_hubert_path`. We also provide the pre-extracted features for the audios in `test_demos/audios` at [URL](https://huggingface.co/datasets/taocode/anitalker_hubert_feature_samples/tree/main) for your testing.

The above information can be found on README.

**Comment by liutaocode** [comment]
If you have trouble extracting the features and have something urgent, you can send them to my email, [liutaw@sjtu.edu.cn](mailto:liutaw@sjtu.edu.cn). I will help you extract them. Please try to keep the audio clips short and don't send too many. Thanks.

**Comment by nitinmukesh** [comment]
I wil not trouble you during your personal time.
The speed is very very fast which is very good.
I guess there are some issues related to eyes focus and lip movement. I got poor results using hubert method.

If I use custom image (using to create intro talking head video with EchoMimic and got good results) the results are very very bad. I guess if you look to update those issues will be gone and this will be used widely.

I am going to do more tests.

![FACE1](https://github.com/user-attachments/assets/0b75364f-3e0e-43c0-a7cf-aec5404c6ef2)

https://github.com/user-attachments/assets/54d5cf88-fa45-4325-a75f-59a056f5d966
