### ISSUE TITLE
Windows tutorial for inference using Hubert method

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#24]
https://www.youtube.com/watch?v=dZRRtnKUUoE

In next video will explain how to prepare images for inference. Use any of the images from attached zip for testing purpose
[images.zip](https://github.com/user-attachments/files/16447250/images.zip)

**Comment by oisilener1982** [comment]
This is the weakness of Anitalker. The proces is so long when using hubert method and there is no full body stitching like in Sadtalker

I might just stick to Sadtalker + Echomimic for now.

**Comment by liutaocode** [comment]
That's cool ~ Thanks. 

> https://www.youtube.com/watch?v=dZRRtnKUUoE
> 
> In next video will explain how to prepare images for inference. Use any of the images from attached zip for testing purpose [images.zip](https://github.com/user-attachments/files/16447250/images.zip)

**Comment by liutaocode** [comment]
> This is the weakness of Anitalker. The proces is so long when using hubert method and there is no full body stitching like in Sadtalker. It would be nice if we can just use any plain audio like mp3 or wav and not use NPY
> 
> I might just stick to Sadtalker + Echomimic +liveportrait for now.

Thank you for your feedback. We have updated the code and integrated the audio feature extraction process into the pipeline, eliminating the need for complex environment setup. We welcome you to try it out.

**Comment by nitinmukesh** [comment]
> This is the weakness of Anitalker. The proces is so long when using hubert method and there is no full body stitching like in Sadtalker. It would be nice if we can just use any plain audio like mp3 or wav and not use NPY
> 
> I might just stick to Sadtalker + Echomimic +liveportrait for now.

Actually it will not be long process. As you see it is released just couple of days back and already many updates are done.
I got even better results with Hubert method. The lip sync definitely need some improvement.
The process is also very fast it's just that few extra steps are needed which will be gone in some time and everything will be automated.
I see potential in this tool.
