### ISSUE TITLE
Preparing image for inference

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#27]
Please refer this repository, all installation steps are documented. I have created a simple Gradio WebUI for image cropping.
Make sure to manually update the output directory path in WebUI.
Once the code is integrated in pipeline this manual step will not be needed.

https://github.com/newgenai79/CropImage 

@liutaocode 

Please could you help adding this in pipeline (crop pipeline) so the manual steps will not be needed.
https://raw.githubusercontent.com/tanshuai0219/EDTalk/main/data_preprocess/crop_image2.py

I tested this with the following dependencies (on Windows 11)
pip install opencv-python==4.10.0.84 dlib==19.24.5 scikit-image==0.24.0

**Comment by liutaocode** [comment]
Thank you very much. This method requires fewer resources than our previous crop method. We'll compare them later and integrate it into our system.
