### ISSUE TITLE
I tried the AniTalker Gradio Interface on Google Colab.

### ISSUE THREAD

**Issue by NeuralFalconYT** [X-LANCE/AniTalker#28]
https://github.com/NeuralFalconYT/AniTalker-Colab

**Comment by nitinmukesh** [comment]
@NeuralFalconYT 

Looks amazing. Please if you could also create Gradio UI for local.

**Comment by liutaocode** [comment]
Thanks for your contribution. This will help users who are not familiar with the code or want to quickly experience it. We will add a link to your link.

**Comment by oisilener1982** [comment]
Please create a gradio webui for locan installtion. Thanks in advance

**Comment by NeuralFalconYT** [comment]
Hi, I tried to set up a local Gradio app interface, but I'm encountering numerous errors configuring CUDA and PyTorch on my system. My GPU is not high-performance, so I'm unable to run the interface locally. However, I will try to modify the Colab code so that we can run it locally as well.
