### ISSUE TITLE
泛化性有点差啊

### ISSUE THREAD

**Issue by Eggwardhan** [X-LANCE/AniTalker#29]
试了几个例子咩一个正常的
![image](https://github.com/user-attachments/assets/11f603e5-19c0-4475-9545-3a58251853ff)
![image](https://github.com/user-attachments/assets/1ba257ab-f2e3-4f3d-8bf5-a5afb0cad48e)

**Comment by nitinmukesh** [comment]
@Eggwardhan 

Please try pre-processing your images using the tool and use the output file for inference.
https://github.com/X-LANCE/AniTalker/issues/27

Also provide details which method you used for inference, MFCC or Hubert?

**Comment by liutaocode** [comment]
> 试了几个例子咩一个正常的 ![image](https://private-user-images.githubusercontent.com/32223217/354288251-11f603e5-19c0-4475-9545-3a58251853ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjQ2NTAsIm5iZiI6MTcyMjU2NDM1MCwicGF0aCI6Ii8zMjIyMzIxNy8zNTQyODgyNTEtMTFmNjAzZTUtMTljMC00NDc1LTk1NDUtM2E1ODI1MTg1M2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAyMDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NGRiYTI1OTY5OWU4Njg0MDUwZTdlODE0OWJhYTczMGMxNTdkYWFlODBiMWFkZWI2YmUyODFmMzU3OGVlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VN6EuWvOja0oe9L9-pnPzeq9fhd20w84ZbQO-S_5gxM) ![image](https://private-user-images.githubusercontent.com/32223217/354288334-1ba257ab-f2e3-4f3d-8bf5-a5afb0cad48e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjQ2NTAsIm5iZiI6MTcyMjU2NDM1MCwicGF0aCI6Ii8zMjIyMzIxNy8zNTQyODgzMzQtMWJhMjU3YWItZjJlMy00ZjNkLThiZjUtYTVhZmIwY2FkNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAyMDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NjQzZDYzYjgzNDE1NGU0NGMxMDU2OTEyYjVlZDY2YTliNzkyNjE4YWY3NzA3OGFlNmE2MWI2NGUyZGEyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yuNrA_8Qm_5igEs0Xsz-q13ccdqKxWPsJAvno2l8ja8)

目前是需要手动 crop 的，麻烦提供下原始的图片，我们看看。为了方便，另外我们也在集成[这里的代码](https://github.com/liutaocode/talking_face_preprocessing?tab=readme-ov-file#facial-part-cropping)，这个 crop 代码和我们训练数据处理是一致的。

Currently, manual cropping is required. Please provide the original image so we can take a look. For convenience, we are also integrating the cropping code from [this repository](https://github.com/liutaocode/talking_face_preprocessing?tab=readme-ov-file#facial-part-cropping). This cropping code is consistent with our training data processing.

**Comment by liutaocode** [comment]
> @Eggwardhan
> 
> Please try pre-processing your images using the tool and use the output file for inference. #27
> 
> Also provide details which method you used for inference, MFCC or Hubert?

Thanks @nitinmukesh . 

Due to your significant contributions to this project, we are now inviting you to become a collaborator and assist us in handling issues and other matters. Thank you very much.

**Comment by nitinmukesh** [comment]
Hello @liutaocode 

Many thanks for your invitation. As you can see I am only a youtuber and don't have any programming knowledge. I maynot be able to contribute anything related to code.
If you think I can help with testing the issue in this section and reviewing posts, I will be more than happy to collaborate.
Please let me know.

**Comment by liutaocode** [comment]
> Hello @liutaocode
> 
> Many thanks for your invitation. As you can see I am only a youtuber and don't have any programming knowledge. I maynot be able to contribute anything related to code. If you think I can help with testing the issue in this section and reviewing posts, I will be more than happy to collaborate. Please let me know.

Thank you for your interest in contributing. Feel free to help in any way you can; any type of contribution is welcomed.

**Comment by Eggwardhan** [comment]
https://github.com/X-LANCE/AniTalker/issues/27 works @nitinmukesh thx a lot
but I want to know have you tried incorporating body movements?

**Comment by nitinmukesh** [comment]
@Eggwardhan 
Thanks for confirming. Please post some output here if no issues. Create another github issue for that.

Body movements is not in scope for talking head and not planned as of now. Current focus is to automate all processes and remove manual image cropping.
