### ISSUE TITLE
Great work! Any plan to release the code and checkpoint? 

### ISSUE THREAD

**Issue by WilTay1** [X-LANCE/AniTalker#3]

**Comment by hedada-hc** [comment]
> _没有提供描述。_

There are currently no open source plans

**Comment by ashish-roopan** [comment]
Looking forward to trying it out once the checkpoints are made public

**Comment by zhanghongyong123456** [comment]
> The weights and code are being organized, and we will make them public as soon as possible.

期待模型发布！！！

**Comment by liutaocode** [comment]
Thanks for your attention. You can check it out now.
