### ISSUE TITLE
Latest updates break the code on Windows

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#36]
I was trying to add auto crop feature in WebUI and found the latest code is no longer working on Windows.

```
(anitalker) C:\temp\AniTalker>python ./code/demo.py --infer_type hubert_audio_only --stage1_checkpoint_path ckpts/stage1.ckpt --stage2_checkpoint_path ckpts/stage2_audio_only_hubert.ckpt --test_image_path test_demos/portraits/monalisa.jpg --test_audio_path test_demos/audios/monalisa.wav --test_hubert_path test_demos/audios_hubert/monalisa.npy --result_path outputs/monalisa_hubert/  --face_sr
Traceback (most recent call last):
  File "C:\temp\AniTalker\code\demo.py", line 297, in <module>
    if torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'
```

**Comment by liutaocode** [comment]
Oh, I apologize. I overlooked the possibility that the 'mps' package might not exist. This issue has been urgently fixed.

**Comment by nitinmukesh** [comment]
@liutaocode 
I found the fix.

In earlier version of torch it 'mps' was not supported but running the following command works

`pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1+cu116 --index-url https://download.pytorch.org/whl/cu116
`

**Comment by nitinmukesh** [comment]
Pull request raise to fix this and several other updates.
https://github.com/X-LANCE/AniTalker/pull/38
