### ISSUE TITLE
Potential issue with MacOS tutorial?

### ISSUE THREAD

**Issue by nitinmukesh** [X-LANCE/AniTalker#37]
I read the following
https://github.com/X-LANCE/AniTalker/blob/main/md_docs/run_on_macOS.md

Section 3. Model Download

It asks to download only stage 1 and 2 checkpoints but missing the following
[chinese-hubert-large](https://huggingface.co/taocode/anitalker_ckpts/tree/main/chinese-hubert-large)

Isn't the above required for audio features ? [hubert_audio_only]

**Comment by liutaocode** [comment]
Thank you for your feedback. I've just revised the macOS README to make the model download description consistent with the main README, and I've also optimized the environment installation instructions. Feel free to ask if you have any other questions.
