### ISSUE TITLE
dlib 

### ISSUE THREAD

**Issue by tjlbx** [X-LANCE/AniTalker#43]
ERROR: Failed building wheel for dlib

**Comment by nitinmukesh** [comment]
Check your python version and see if you find pre-built wheel. Python 3.9 version wheel is there

https://github.com/sachadee/Dlib

**Comment by tjlbx** [comment]
> Check your python version and see if you find pre-built wheel. Python 3.9 version wheel is there
> 
> https://github.com/sachadee/Dlib

I download the whl, but I meet another error:
PS D:\ProgramData\miniconda3> python -m pip install .\dlib-19.22.99-cp39-cp39-win_amd64.whl
ERROR: dlib-19.22.99-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

**Comment by tjlbx** [comment]
> Check your python version and see if you find pre-built wheel. Python 3.9 version wheel is there
> 
> https://github.com/sachadee/Dlib

Thanks!!!

**Comment by nitinmukesh** [comment]
@tjlbx 

It worked?

**Comment by nitinmukesh** [comment]
Closing as solution is provided.
