### ISSUE TITLE
What is the basic requirement of GPU and memory?

### ISSUE THREAD

**Issue by qkxie** [X-LANCE/AniTalker#5]
Which kind of GPU should I use? 4090 or just mac M1?

**Comment by nyck33** [comment]
I'm also wondering with my Nvidia Geforce GTX 1650 (4GB VRAM) and 20 GB main memory.  But also wondering approximately how long it would take on Colab Pro or Kaggle's GPU's.

**Comment by liutaocode** [comment]
We have only tested on the 3060 Ti as the minimum hardware. Our method doesn't require a large number of parameters like Stable Diffusion, so the GPU requirements are not high.

**Comment by nitinmukesh** [comment]
@qkxie @nyck33 

The GPU requirment is very less. I have tested on 8 GB VRAM and still a lot of memory available. Should definitely work on 6 GB VRAM and maybe for short audio 4 GB should be enough.

**Comment by qkxie** [comment]
how about a macbook air M2?
@nitinmukesh

**Comment by nitinmukesh** [comment]
@qkxie 

I am not sure about Mac, never used so no idea. If this can be installed on Mac I guess it should work.
Please give it a try and let us know the results.

**Comment by nitinmukesh** [comment]
Closing as no updates in this topic
